import { useState, useEffect } from 'react';
import { Paper, Typography, Box, CircularProgress, Chip, Divider } from '@mui/material';
import PsychologyIcon from '@mui/icons-material/Psychology';

interface ZoneData {
  postcode: string;
  metrics: {
    growth_rate: number;
    crime_rate: number;
    infrastructure_score: number;
    interest_rate: number;
    wages: number;
    housing_supply: string;
    immigration: string;
    risk_score: number;
    trend: string;
  };
  ai_insights?: {
    summary: string;
    full_analysis: string;
    confidence: number;
    generated_by: string;
  };
}

interface AIInsightsProps {
  zoneData: ZoneData;
}

const AIInsights = ({ zoneData }: AIInsightsProps) => {
  const [loading, setLoading] = useState<boolean>(false);

  return (
    <Paper elevation={3} sx={{ p: 2, mt: 2 }}>
      <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
        <PsychologyIcon sx={{ mr: 1, color: 'primary.main' }} />
        <Typography variant="h6" sx={{ flexGrow: 1 }}>
          AI Analysis
        </Typography>
        {zoneData.ai_insights && (
          <Chip
            label={`${zoneData.ai_insights.confidence}% Confidence`}
            color="primary"
            size="small"
            sx={{ ml: 1 }}
          />
        )}
      </Box>

      {loading ? (
        <Box display="flex" justifyContent="center" p={2}>
          <CircularProgress size={24} />
        </Box>
      ) : zoneData.ai_insights ? (
        <Box>
          <Typography variant="body1" color="text.primary" paragraph>
            {zoneData.ai_insights.summary}
          </Typography>
          
          <Divider sx={{ my: 2 }} />
          
          <Typography variant="body2" color="text.secondary">
            {zoneData.ai_insights.full_analysis}
          </Typography>
          
          <Box sx={{ mt: 2, display: 'flex', alignItems: 'center' }}>
            <Chip
              label={`Generated by ${zoneData.ai_insights.generated_by}`}
              variant="outlined"
              size="small"
              color="primary"
            />
          </Box>
        </Box>
      ) : (
        <Typography variant="body1" color="text.secondary">
          No AI insights available for this zone.
        </Typography>
      )}
    </Paper>
  );
};

export default AIInsights; 